/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Asus
 */
public class HomeUI extends javax.swing.JFrame {

    
    public HomeUI() {
        initComponents();
    }
    
    /**
     *
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        no_canteen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        no_floor = new javax.swing.JTextField();
        no_elevator = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        enter_but = new javax.swing.JButton();
        IMG = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(186, 255, 235));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        no_canteen.setFont(new java.awt.Font("Arca Majora 3 Bold", 1, 25)); // NOI18N
        no_canteen.setText("2");
        no_canteen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_canteenActionPerformed(evt);
            }
        });
        getContentPane().add(no_canteen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 300, 33));

        jLabel6.setFont(new java.awt.Font("Arca Majora 3 Bold", 1, 25)); // NOI18N
        jLabel6.setText("NUMBER OF FLOOR");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arca Majora 3 Bold", 1, 90)); // NOI18N
        jLabel1.setText("ELEVATOR SYSTEM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arca Majora 3 Bold", 1, 40)); // NOI18N
        jLabel2.setText("BY S4A1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arca Majora 3 Bold", 1, 25)); // NOI18N
        jLabel3.setText("NUMBER OF FLOOR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arca Majora 3 Bold", 1, 25)); // NOI18N
        jLabel4.setText("NUMBER OF ELEVATORS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        no_floor.setFont(new java.awt.Font("Arca Majora 3 Bold", 1, 25)); // NOI18N
        no_floor.setText("15");
        no_floor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_floorActionPerformed(evt);
            }
        });
        getContentPane().add(no_floor, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 300, 33));

        no_elevator.setFont(new java.awt.Font("Arca Majora 3 Bold", 1, 25)); // NOI18N
        no_elevator.setText("3");
        no_elevator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_elevatorActionPerformed(evt);
            }
        });
        getContentPane().add(no_elevator, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 300, 33));

        jLabel5.setFont(new java.awt.Font("Arca Majora 3 Bold", 1, 25)); // NOI18N
        jLabel5.setText("OPTION");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        enter_but.setBackground(new java.awt.Color(0, 0, 0));
        enter_but.setFont(new java.awt.Font("Arca Majora 3 Bold", 1, 30)); // NOI18N
        enter_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/02.gif"))); // NOI18N
        enter_but.setText("ENTER");
        enter_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_butActionPerformed(evt);
            }
        });
        getContentPane().add(enter_but, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 680, 50));

        IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GG.gif"))); // NOI18N
        IMG.setText("jLabel7");
        getContentPane().add(IMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 630, 500));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ABOUT_US.gif"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 683, 130, 30));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/01.gif"))); // NOI18N
        BG.setText("jLabel6");
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -250, 1400, 970));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void no_floorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_floorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_floorActionPerformed

    private void enter_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_butActionPerformed
        
        Building.setE_F_C(Integer.parseInt(no_elevator.getText()), Integer.parseInt(no_floor.getText()), Integer.parseInt(no_canteen.getText()));
        Building.init();
        Building.mainui = new MainUI(); 
        this.dispose();
        Building.mainui.setVisible (true);
        Building.run();
        
    }//GEN-LAST:event_enter_butActionPerformed

    private void no_elevatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_elevatorActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_no_elevatorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Members buttom = new Members();
       buttom.setVisible (true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void no_canteenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_canteenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_canteenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel IMG;
    private javax.swing.JButton enter_but;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField no_canteen;
    private javax.swing.JTextField no_elevator;
    private javax.swing.JTextField no_floor;
    // End of variables declaration//GEN-END:variables
}
