

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
    import java.awt.Graphics;
    import java.awt.Color;
    import java.awt.Label;
import java.awt.Point;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
    

/**
 *
 * @author Asus
 */
public class MainUI extends javax.swing.JFrame {
    
    int speed = 1;
    /**
     * Creates new form UI1
     */
    public MainUI() {
        initComponents();
    }

    
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSlider2 = new javax.swing.JSlider();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        label17 = new java.awt.Label();
        Door1 = new javax.swing.JPanel();
        door1 = new javax.swing.JLabel();
        door2 = new javax.swing.JLabel();
        Door2 = new javax.swing.JPanel();
        door3 = new javax.swing.JLabel();
        door4 = new javax.swing.JLabel();
        Door3 = new javax.swing.JPanel();
        door5 = new javax.swing.JLabel();
        door6 = new javax.swing.JLabel();
        f1 = new javax.swing.JLabel();
        f2 = new javax.swing.JLabel();
        f3 = new javax.swing.JLabel();
        f4 = new javax.swing.JLabel();
        f5 = new javax.swing.JLabel();
        f6 = new javax.swing.JLabel();
        f7 = new javax.swing.JLabel();
        f8 = new javax.swing.JLabel();
        f9 = new javax.swing.JLabel();
        f10 = new javax.swing.JLabel();
        f11 = new javax.swing.JLabel();
        f12 = new javax.swing.JLabel();
        f13 = new javax.swing.JLabel();
        f14 = new javax.swing.JLabel();
        f15 = new javax.swing.JLabel();
        Human = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Statee1 = new java.awt.Label();
        Queuee1 = new java.awt.Label();
        Hue1 = new java.awt.Label();
        jLabel4 = new javax.swing.JLabel();
        State2e2 = new java.awt.Label();
        Queue2e2 = new java.awt.Label();
        Hu2e2 = new java.awt.Label();
        jLabel3 = new javax.swing.JLabel();
        State3e3 = new java.awt.Label();
        Queue3e3 = new java.awt.Label();
        Hu3e3 = new java.awt.Label();
        stop_button = new javax.swing.JToggleButton();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arca Majora 3 Bold", 0, 20)); // NOI18N
        jLabel1.setText("SPEED");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 50, -1, 30));

        jSlider2.setBackground(new java.awt.Color(255, 255, 204));
        jSlider2.setForeground(new java.awt.Color(0, 0, 0));
        jSlider2.setMajorTickSpacing(1);
        jSlider2.setMaximum(5);
        jSlider2.setMinimum(1);
        jSlider2.setMinorTickSpacing(1);
        jSlider2.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider2.setPaintLabels(true);
        jSlider2.setPaintTicks(true);
        jSlider2.setValue(1);
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });
        jPanel1.add(jSlider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 80, 90, 210));

        jButton2.setBackground(new java.awt.Color(255, 255, 204));
        jButton2.setFont(new java.awt.Font("Arca Majora 3 Bold", 1, 26)); // NOI18N
        jButton2.setText("HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 325, 128, 73));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setBackground(new java.awt.Color(102, 51, 0));
        label1.setEnabled(false);
        jPanel2.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 5));

        label2.setBackground(new java.awt.Color(102, 51, 0));
        label2.setEnabled(false);
        jPanel2.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 46, 1270, 5));

        label3.setBackground(new java.awt.Color(102, 51, 0));
        label3.setEnabled(false);
        jPanel2.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 92, 1270, 5));

        label4.setBackground(new java.awt.Color(102, 51, 0));
        label4.setEnabled(false);
        jPanel2.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 138, 1270, 5));

        label5.setBackground(new java.awt.Color(102, 51, 0));
        label5.setEnabled(false);
        jPanel2.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 184, 1270, 5));

        label6.setBackground(new java.awt.Color(102, 51, 0));
        label6.setEnabled(false);
        jPanel2.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 1270, 5));

        label7.setBackground(new java.awt.Color(102, 51, 0));
        label7.setEnabled(false);
        jPanel2.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 276, 1270, 5));

        label8.setBackground(new java.awt.Color(102, 51, 0));
        label8.setEnabled(false);
        jPanel2.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 322, 1270, 5));

        label9.setBackground(new java.awt.Color(102, 51, 0));
        label9.setEnabled(false);
        jPanel2.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 368, 1270, 5));

        label10.setBackground(new java.awt.Color(102, 51, 0));
        label10.setEnabled(false);
        jPanel2.add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 414, 1270, 5));

        label11.setBackground(new java.awt.Color(102, 51, 0));
        label11.setEnabled(false);
        jPanel2.add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 414, 1270, 5));

        label12.setBackground(new java.awt.Color(102, 51, 0));
        label12.setEnabled(false);
        jPanel2.add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 1270, 5));

        label13.setBackground(new java.awt.Color(102, 51, 0));
        label13.setEnabled(false);
        jPanel2.add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 506, 1270, 5));

        label14.setBackground(new java.awt.Color(102, 51, 0));
        label14.setEnabled(false);
        jPanel2.add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 552, 1270, 5));

        label15.setBackground(new java.awt.Color(102, 51, 0));
        label15.setEnabled(false);
        jPanel2.add(label15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 598, 1270, 5));

        label16.setBackground(new java.awt.Color(102, 51, 0));
        label16.setEnabled(false);
        jPanel2.add(label16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 644, 1270, 5));

        label17.setBackground(new java.awt.Color(102, 51, 0));
        label17.setEnabled(false);
        jPanel2.add(label17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 1270, 5));

        Door1.setBackground(new java.awt.Color(0, 0, 0));
        Door1.setDoubleBuffered(false);
        Door1.setEnabled(false);
        Door1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                Door1ComponentMoved(evt);
            }
        });

        door1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                door1ComponentMoved(evt);
            }
        });
        Door1.add(door1);
        Door1.add(door2);

        jPanel2.add(Door1, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 645, 86, 50));

        Door2.setBackground(new java.awt.Color(0, 0, 0));
        Door2.setDoubleBuffered(false);
        Door2.setEnabled(false);
        Door2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                Door2ComponentMoved(evt);
            }
        });
        Door2.add(door3);
        Door2.add(door4);

        jPanel2.add(Door2, new org.netbeans.lib.awtextra.AbsoluteConstraints(839, 645, 86, 50));

        Door3.setBackground(new java.awt.Color(0, 0, 0));
        Door3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                Door3ComponentMoved(evt);
            }
        });
        Door3.add(door5);
        Door3.add(door6);

        jPanel2.add(Door3, new org.netbeans.lib.awtextra.AbsoluteConstraints(959, 645, 86, 50));

        f1.setFont(new java.awt.Font("Arca Majora 3 Bold", 1, 18)); // NOI18N
        f1.setText("1ST Floor");
        jPanel2.add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, -1, -1));

        f2.setFont(new java.awt.Font("Arca Majora 3 Bold", 1, 18)); // NOI18N
        f2.setText("2ND Floor");
        jPanel2.add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 605, -1, -1));

        f3.setFont(new java.awt.Font("Arca Majora 3 Bold", 1, 18)); // NOI18N
        f3.setText("3RD Floor");
        jPanel2.add(f3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 558, -1, -1));
        f3.getAccessibleContext().setAccessibleDescription("");

        f4.setFont(new java.awt.Font("Arca Majora 3 Bold", 1, 18)); // NOI18N
        f4.setText("4TH Floor");
        jPanel2.add(f4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 512, -1, -1));

        f5.setFont(new java.awt.Font("Arca Majora 3 Bold", 1, 18)); // NOI18N
        f5.setText("5TH Floor");
        jPanel2.add(f5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 466, -1, -1));

        f6.setFont(new java.awt.Font("Arca Majora 3 Bold", 1, 18)); // NOI18N
        f6.setText("6TH Floor");
        jPanel2.add(f6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));

        f7.setFont(new java.awt.Font("Arca Majora 3 Bold", 1, 18)); // NOI18N
        f7.setText("7TH Floor");
        jPanel2.add(f7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 375, -1, -1));

        f8.setFont(new java.awt.Font("Arca Majora 3 Bold", 1, 18)); // NOI18N
        f8.setText("8TH Floor");
        jPanel2.add(f8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 328, -1, -1));

        f9.setFont(new java.awt.Font("Arca Majora 3 Bold", 1, 18)); // NOI18N
        f9.setText("9TH Floor");
        jPanel2.add(f9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 282, -1, -1));

        f10.setFont(new java.awt.Font("Arca Majora 3 Bold", 1, 18)); // NOI18N
        f10.setText("10TH Floor");
        jPanel2.add(f10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 236, -1, -1));

        f11.setFont(new java.awt.Font("Arca Majora 3 Bold", 1, 18)); // NOI18N
        f11.setText("11TH Floor");
        jPanel2.add(f11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        f12.setFont(new java.awt.Font("Arca Majora 3 Bold", 1, 18)); // NOI18N
        f12.setText("12TH Floor");
        jPanel2.add(f12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 144, -1, -1));

        f13.setFont(new java.awt.Font("Arca Majora 3 Bold", 1, 18)); // NOI18N
        f13.setText("13TH Floor");
        jPanel2.add(f13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 98, -1, -1));

        f14.setFont(new java.awt.Font("Arca Majora 3 Bold", 1, 18)); // NOI18N
        f14.setText("14TH Floor");
        jPanel2.add(f14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 52, -1, -1));

        f15.setFont(new java.awt.Font("Arca Majora 3 Bold", 1, 18)); // NOI18N
        f15.setText("15TH Floor");
        jPanel2.add(f15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        Human.setEnabled(false);
        Human.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                HumanComponentMoved(evt);
            }
        });
        jPanel2.add(Human, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 665, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/01.gif"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 86, 690));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/01.gif"))); // NOI18N
        jLabel6.setText("jLabel5");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 0, 86, 690));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/01.gif"))); // NOI18N
        jLabel7.setText("jLabel5");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 86, 690));

        jLabel8.setText("jLabel8");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 670, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1190, 700));

        time.setFont(new java.awt.Font("Arca Majora 3 Bold", 1, 14)); // NOI18N
        time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time.setText("jLabel17");
        time.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        time.setRequestFocusEnabled(false);
        time.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 10, 120, 40));

        jLabel2.setText("Elevator1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 410, -1, -1));

        Statee1.setText("State :");
        jPanel1.add(Statee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 435, -1, -1));

        Queuee1.setText("Queue :");
        jPanel1.add(Queuee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 455, -1, -1));

        Hue1.setText("No. of people :");
        jPanel1.add(Hue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 475, -1, -1));

        jLabel4.setText("Elevator2");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 515, -1, -1));

        State2e2.setText("State :");
        jPanel1.add(State2e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 540, -1, -1));

        Queue2e2.setText("Queue :");
        jPanel1.add(Queue2e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 560, -1, -1));

        Hu2e2.setText("No. of people :");
        jPanel1.add(Hu2e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 580, -1, -1));

        jLabel3.setText("Elevator3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 620, -1, -1));

        State3e3.setText("State :");
        jPanel1.add(State3e3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 640, -1, -1));

        Queue3e3.setText("Queue :");
        jPanel1.add(Queue3e3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 660, -1, -1));

        Hu3e3.setText("No. of people :");
        jPanel1.add(Hu3e3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 680, -1, -1));

        stop_button.setText("STOP");
        stop_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stop_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(stop_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1239, 300, 70, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Door1ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Door1ComponentMoved

    }//GEN-LAST:event_Door1ComponentMoved

    private void door1ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_door1ComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_door1ComponentMoved

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        HomeUI buttom = new HomeUI();
        buttom.setVisible (true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        int value = jSlider2.getValue();
        if(value == 1 ) Building.setTimeframe(10000);
        if(value == 2 ) Building.setTimeframe(7500);   
        if(value == 3 ) Building.setTimeframe(5000);
        if(value == 4 ) Building.setTimeframe(2500);
        if(value == 5 ) Building.setTimeframe(1000);   
    }//GEN-LAST:event_jSlider2StateChanged

    private void HumanComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_HumanComponentMoved

    }//GEN-LAST:event_HumanComponentMoved

    private void Door2ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Door2ComponentMoved

    }//GEN-LAST:event_Door2ComponentMoved

    private void Door3ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Door3ComponentMoved

    }//GEN-LAST:event_Door3ComponentMoved

    private void stop_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stop_buttonActionPerformed
        if(stop_button.isSelected()) try {
            Building.stop();
        } catch (InterruptedException ex) {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        else Building.unstop();
    }//GEN-LAST:event_stop_buttonActionPerformed
    public synchronized void setInfo(){
        int position = Building.elevator[0].getPosition();
        JLabel[] flabel = {f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13,f14,f15};
        Point xy;
        int x;
        int y;
        
        for(int i =0;i<Building.num_elevator;i++){
            position = Building.elevator[i].getPosition();
            
            if(i==0){
                xy = Door1.getLocation();
                x = xy.x;
                y = xy.y;
                Door1.setLocation(x, position);
                Statee1.setText("State : "+Building.elevator[i].getState());
                Hue1.setText("No. of people : " + Building.elevator[i].getPsize());
                if(!Building.elevator[i].isQueueEmpty())
                    Queuee1.setText("Queue : "+Building.elevator[i].getFirstFloor());
                else Queuee1.setText("Queue : Empty");
                
            }
            if(i==1){
                xy = Door2.getLocation();
                x = xy.x;
                y = xy.y;
                Door2.setLocation(x, position);
                State2e2.setText("State : "+Building.elevator[i].getState());
                Hu2e2.setText("No. of people : " + Building.elevator[i].getPsize());
                if(!Building.elevator[i].isQueueEmpty())    
                    Queue2e2.setText("Queue : "+Building.elevator[i].getFirstFloor());
                else Queue2e2.setText("Queue : Empty");
            }
            if(i==2){
                xy = Door3.getLocation();
                x = xy.x;
                y = xy.y;
                Door3.setLocation(x, position);
                State3e3.setText("State : "+Building.elevator[i].getState());
                Hu3e3.setText("No. of people : " + Building.elevator[i].getPsize());
                if(!Building.elevator[i].isQueueEmpty())
                    Queue3e3.setText("Queue : "+Building.elevator[i].getFirstFloor());
                else Queue3e3.setText("Queue : Empty");
            }
            flabel[(Building.food_floor)-1].setText(Building.food_floor+"TH Floor" + " Canteen");
            
        }
                  
    }
    
    public void setTime(){
        Clock clock = new Clock();
        time.setText(clock.getTimev()); 
    }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
                
            }
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Door1;
    private javax.swing.JPanel Door2;
    private javax.swing.JPanel Door3;
    private java.awt.Label Hu2e2;
    private java.awt.Label Hu3e3;
    private java.awt.Label Hue1;
    private javax.swing.JLabel Human;
    private java.awt.Label Queue2e2;
    private java.awt.Label Queue3e3;
    private java.awt.Label Queuee1;
    private java.awt.Label State2e2;
    private java.awt.Label State3e3;
    private java.awt.Label Statee1;
    private javax.swing.JLabel door1;
    private javax.swing.JLabel door2;
    private javax.swing.JLabel door3;
    private javax.swing.JLabel door4;
    private javax.swing.JLabel door5;
    private javax.swing.JLabel door6;
    private javax.swing.JLabel f1;
    private javax.swing.JLabel f10;
    private javax.swing.JLabel f11;
    private javax.swing.JLabel f12;
    private javax.swing.JLabel f13;
    private javax.swing.JLabel f14;
    private javax.swing.JLabel f15;
    private javax.swing.JLabel f2;
    private javax.swing.JLabel f3;
    private javax.swing.JLabel f4;
    private javax.swing.JLabel f5;
    private javax.swing.JLabel f6;
    private javax.swing.JLabel f7;
    private javax.swing.JLabel f8;
    private javax.swing.JLabel f9;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSlider jSlider2;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JToggleButton stop_button;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables


}
