/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Spectrum
 */
public class Members extends javax.swing.JFrame {

    /**
     * Creates new form Members
     */
    public Members() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        fon = new javax.swing.JLabel();
        big = new javax.swing.JLabel();
        boeing = new javax.swing.JLabel();
        fluke = new javax.swing.JLabel();
        man_u = new javax.swing.JLabel();
        n_man = new javax.swing.JLabel();
        n_fluke = new javax.swing.JLabel();
        n_bo = new javax.swing.JLabel();
        n_big = new javax.swing.JLabel();
        n_fon = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 60)); // NOI18N
        jLabel2.setText("DEVELOPER TEAM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        fon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fon.gif"))); // NOI18N
        getContentPane().add(fon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 250, -1, -1));

        big.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BIG.gif"))); // NOI18N
        getContentPane().add(big, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 250, -1, -1));

        boeing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Boeing.gif"))); // NOI18N
        getContentPane().add(boeing, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));

        fluke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fluke.gif"))); // NOI18N
        getContentPane().add(fluke, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        man_u.setIcon(new javax.swing.ImageIcon(getClass().getResource("/man_u.gif"))); // NOI18N
        getContentPane().add(man_u, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        n_man.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        n_man.setText("Saratoon  Khunsanit 60090500423");
        getContentPane().add(n_man, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 470, -1, -1));

        n_fluke.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        n_fluke.setText("Supakit  Soijinda 60090500425");
        getContentPane().add(n_fluke, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 470, -1, -1));

        n_bo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        n_bo.setText("Anawin Bunyavanich 60090500435");
        getContentPane().add(n_bo, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 470, -1, -1));

        n_big.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        n_big.setText("Siwapong  Kopkit 60090500447");
        getContentPane().add(n_big, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, -1, -1));

        n_fon.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        n_fon.setText("Saowalak  Janchaipuek 60090500451");
        getContentPane().add(n_fon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1025, 470, -1, -1));

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 643, 760, 60));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg_home.gif"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       HomeUI buttom = new HomeUI();
       buttom.setVisible (true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Members.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Members.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Members.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Members.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Members().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel big;
    private javax.swing.JLabel boeing;
    private javax.swing.JLabel fluke;
    private javax.swing.JLabel fon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel man_u;
    private javax.swing.JLabel n_big;
    private javax.swing.JLabel n_bo;
    private javax.swing.JLabel n_fluke;
    private javax.swing.JLabel n_fon;
    private javax.swing.JLabel n_man;
    // End of variables declaration//GEN-END:variables
}
